package com.example.kitsuapi.presentation.model.manga

import com.example.domain.model.manga.MangaAttributesModel

data class MangaAttributesUI(
    val abbreviatedTitles: List<String>? = listOf(),
    val ageRating: String? = "",
    val ageRatingGuide: Any? = Any(),
    val averageRating: String? = "",
    val canonicalTitle: String? = "",
    val chapterCount: Int? = 0,
    val coverImageTopOffset: Int? = 0,
    val createdAt: String? = "",
    val description: String? = "",
    val endDate: String? = "",
    val favoritesCount: Int? = 0,
    val mangaType: String? = "",
    val nextRelease: Any? = Any(),
    val popularityRank: Int? = 0,
    val posterImage: MangaPosterImageUI? = MangaPosterImageUI(),
    val ratingRank: Int? = 0,
    val serialization: String? = "",
    val slug: String? = "",
    val startDate: String? = "",
    val status: String? = "",
    val subtype: String? = "",
    val synopsis: String? = "",
    val tba: Any? = Any(),
    val titles: MangaTitlesUI? = MangaTitlesUI(),
    val updatedAt: String? = "",
    val userCount: Int? = 0,
    val volumeCount: Int? = 0
)

fun MangaAttributesModel.toUI() = MangaAttributesUI(
    abbreviatedTitles,
    ageRating,
    ageRatingGuide,
    averageRating,
    canonicalTitle,
    chapterCount,
    coverImageTopOffset,
    createdAt,
    description,
    endDate,
    favoritesCount,
    mangaType,
    nextRelease,
    popularityRank,
    posterImage?.toUI(),
    ratingRank,
    serialization,
    slug,
    startDate,
    status,
    subtype,
    synopsis,
    tba,
    titles?.toUI(),
    updatedAt,
    userCount,
    volumeCount
)